### ISSUE TITLE
having problem with the code 

### ISSUE THREAD

**Issue by henrymiles123** [SindreMA/ChannelLinkerBot#3]
![1](https://user-images.githubusercontent.com/40438785/41676037-5f1554a0-7492-11e8-8ff3-8420b35e302e.JPG)

**Comment by SindreMA** [comment]
Hey, 

Try this version instead, have gone away from the "tag database system".

Have redone the bot in a newer API Wrapper.
Have also converted to bot to c#, for easier use.

[CSharp_ChannelLinkerBotv3.zip](https://github.com/SindreMA/ChannelLinkerBot/files/2169284/CSharp_ChannelLinkerBotv3.zip)

**Comment by SindreMA** [comment]
Feel free to add me on discord should you need any more help : SindreMA#9630
