### ISSUE TITLE
User to channel

### ISSUE THREAD

**Issue by itsmadsen** [SindreMA/ChannelLinkerBot#4]
@sindreMA is it possible to have only 1 person from a channel sent to another. Let's say a timer bot sent across to another room? If so how. I've put user ID to the room ID via link but says error when I view links.

The .help command says something about it at the bottom but I'm confused.

**Comment by SindreMA** [comment]
The way the bot is build, it needs to be in a guild.

All the settings and links you set are saved with the Guild ID.
Therefor you cant connect a User DM to a guild channel.

What you can do is to Create a private channel where only you and the bot have access, then you can link that to the channel you want.

The thing in the .help command: "(You can use [USER] and [CHANNEL] to make it specifi who and where it came from)"
That is for the prefix :  ".Prefix [prefix message here] (Lets you make the bot say something before it repeats the message)"
That way you can do ".prefix Message was sent in  [CHANNEL] from [USER]"
